//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartverket.ShapeChange.EA.Addin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formGml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formGml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.ShapeChange.EA.Addin.Resources.formGml", typeof(formGml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve application directory..
        /// </summary>
        internal static string applicationDirectoryErrorMessage {
            get {
                return ResourceManager.GetString("applicationDirectoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve EA project directory..
        /// </summary>
        internal static string eaProjectDirectoryErrorMessage {
            get {
                return ResourceManager.GetString("eaProjectDirectoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekttype.
        /// </summary>
        internal static string featureCatalogueFeatureTerm {
            get {
                return ResourceManager.GetString("featureCatalogueFeatureTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.docx.
        /// </summary>
        internal static string featureCatalogueTemplateFilename {
            get {
                return ResourceManager.GetString("featureCatalogueTemplateFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy config files to {0}.
        /// </summary>
        internal static string logMessageCopyConfigFiles {
            get {
                return ResourceManager.GetString("logMessageCopyConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start config....
        /// </summary>
        internal static string logMessageStartConfig {
            get {
                return ResourceManager.GetString("logMessageStartConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged values missing for correct generation. Please update tagged values..
        /// </summary>
        internal static string missingTaggedValuesMessage {
            get {
                return ResourceManager.GetString("missingTaggedValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kartverket.no/geodataarbeid/Standarder/SOSI/Programmer-og-verktoy/.
        /// </summary>
        internal static string shapeChangeAddInHelpUrl {
            get {
                return ResourceManager.GetString("shapeChangeAddInHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templates.
        /// </summary>
        internal static string templatesDirectory {
            get {
                return ResourceManager.GetString("templatesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding must be set. I.e. &apos;iso19136_2007&apos; or &apos;iso19136_2007_INSPIRE_Extensions&apos;.
        /// </summary>
        internal static string validateEncodingErrorMessage {
            get {
                return ResourceManager.GetString("validateEncodingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace must be set. I.e. http://skjema.geonorge.no/sosi/produktspesifikasjon/navn.
        /// </summary>
        internal static string validateNamespaceErrorMessage {
            get {
                return ResourceManager.GetString("validateNamespaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be set. I.e. 4.3 or 1.0RC.
        /// </summary>
        internal static string validateVersionErrorMessage {
            get {
                return ResourceManager.GetString("validateVersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xmlns must be set. Usually sosi.
        /// </summary>
        internal static string validateXmlnsErrorMessage {
            get {
                return ResourceManager.GetString("validateXmlnsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xsd file must have a name. I.e. &apos;name.xsd&apos;.
        /// </summary>
        internal static string validateXsdErrorMessage {
            get {
                return ResourceManager.GetString("validateXsdErrorMessage", resourceCulture);
            }
        }
    }
}
